<section class="banner">
	<div class="container banner__container">
		<div class="banner__content">
			<h2>#New summer collection 2019</h2>
			<h1>Arrivals sales</h1>
			<a href="#">Shop now</a>
		</div>

		<div class="banner__img-shop">
			<img src="images/model_7.png">
		</div>				
	</div>
</section>

<section class="page">
	<div class="container">
		<a href="index.html">Home</a>
		<span>/</span>
		<span>About</span>
	</div>
</section>

<section class="about container">
	<div class="about__content">
		<div class="about__content__itens">
			<div>
				<i class="fas fa-truck fa-3x"></i>
			</div>

			<div>
				<h3>Free shipping</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
			</div>
		</div>

		<div class="about__content__itens">
			<div>
				<i class="fas fa-undo fa-3x"></i>
			</div>

			<div>
				<h3>Free Returns</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
			</div>
		</div>

		<div class="about__content__itens">
			<div>
				<i class="fas fa-question fa-3x"></i>
			</div>

			<div>
				<h3>Costumer Support</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
			</div>
		</div>
	</div>

	<div class="about__start">
		<div>
			<img src="images/blog_1.jpg">
		</div>

		<div>
			<h2>How we Started</h2>
			<p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius repellat, dicta at laboriosam, nemo exercitationem itaque eveniet architecto cumque, deleniti commodi molestias repellendus quos sequi hic fugiat asperiores illum. Atque, in, fuga excepturi corrupti error corporis aliquam unde nostrum quas.
			</p>
			<p>
				Accusantium dolor ratione maiores est deleniti nihil? Dignissimos est, sunt nulla illum autem in, quibusdam cumque recusandae, laudantium minima repellendus.
			</p>
		</div>
	</div>
</section>

<section class="team container">
	<h2>The Team</h2>

	<div class="team__container">
		<div>
			<img src="images/person_1.jpg">
			<h3>Elizabeth Graham</h3>
			<span>CEO/Co-founder</span>
			<p>
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio recusandae doloribus ut fugit officia voluptate soluta.
			</p>
		</div>

		<div>
			<img src="images/person_2.jpg">
			<h3>Jennifer Greive</h3>
			<span>Co-founder</span>
			<p>
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio recusandae doloribus ut fugit officia voluptate soluta.
			</p>
		</div>

		<div>
			<img src="images/person_3.jpg">
			<h3>Patrick Marx</h3>
			<span>Marketing</span>
			<p>
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio recusandae doloribus ut fugit officia voluptate soluta.
			</p>
		</div>

		<div>
			<img src="images/person_4.jpg">
			<h3>Mike Coolbert</h3>
			<span>Sales Manager</span>
			<p>
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio recusandae doloribus ut fugit officia voluptate soluta.
			</p>
		</div>
	</div>
</section>
