<section class="banner">
	<div class="page__inner grid grid--autofit grid--gap-2">
		<div class="banner__content">
			<h2 class="banner__sub">#New summer collection 2019</h2>
			<h1 class="banner__title">Arrivals sales</h1>
			<a class="btn btn--size-md btn--black" href="#">Shop now</a>
		</div>

		<div class="banner__img">
			<img src="images/model_7.png">
		</div>				
	</div>
</section>

<section class="link-back">
	<div class="page__inner">
		<a class="link-back__btn" href="/">Home</a>
		<span class="link-back--mx">/</span>
		<span class="link-back--mx">About</span>
	</div>
</section>

<section class="page__inner page__section">
	<div class="grid grid--col-3 grid--gap-2">
		<div class="grid grid--col-1-5">
			<div class="box__title grid grid--center-self">
				<i class="fas fa-truck fa-3x"></i>
			</div>

			<div class="box__content">
				<h3 class="box__sub">Free shipping</h3>
				<p class="box__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
			</div>
		</div>

		<div class="grid grid--col-1-5">
			<div class="box__title grid grid--center-self">
				<i class="fas fa-undo fa-3x"></i>
			</div>

			<div class="box__content">
				<h3 class="box__sub">Free Returns</h3>
				<p class="box__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
			</div>
		</div>

		<div class="grid grid--col-1-5">
			<div class="box__title grid grid--center-self">
				<i class="fas fa-question fa-3x"></i>
			</div>

			<div class="box__content">
				<h3 class="box__sub">Costumer Support</h3>
				<p class="box__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
			</div>
		</div>
	</div>

	<div class="box--mt-4 grid grid--col-2 grid--gap-2">
		<img class="box__img" src="images/blog_1.jpg">

		<div>
			<h2 class="title__sub">How we Started</h2>
			<p class="title__lines">
				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius repellat, dicta at laboriosam, nemo exercitationem itaque eveniet architecto cumque, deleniti commodi molestias repellendus quos sequi hic fugiat asperiores illum. Atque, in, fuga excepturi corrupti error corporis aliquam unde nostrum quas.
			</p>
			
			<p class="title__lines">
				Accusantium dolor ratione maiores est deleniti nihil? Dignissimos est, sunt nulla illum autem in, quibusdam cumque recusandae, laudantium minima repellendus.
			</p>
		</div>
	</div>
</section>

<section class="page__inner page__section">
	<h2 class="title__sub title__sub--center">The Team</h2>

	<div class="grid grid--col-4 grid--gap-2">
		<div class="team">
			<img class="team__img" src="images/person_1.jpg">
			<h3 class="team__name">Elizabeth Graham</h3>
			<span class="team__ocupation">CEO/Co-founder</span>
			<p class="team__text">
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio recusandae doloribus ut fugit officia voluptate soluta.
			</p>
		</div>

		<div class="team">
			<img class="team__img" src="images/person_2.jpg">
			<h3 class="team__name">Jennifer Greive</h3>
			<span class="team__ocupation">Co-founder</span>
			<p class="team__text">
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio recusandae doloribus ut fugit officia voluptate soluta.
			</p>
		</div>

		<div class="team">
			<img class="team__img" src="images/person_3.jpg">
			<h3 class="team__name">Patrick Marx</h3>
			<span class="team__ocupation">Marketing</span>
			<p class="team__text">
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio recusandae doloribus ut fugit officia voluptate soluta.
			</p>
		</div>

		<div class="team">
			<img class="team__img" src="images/person_4.jpg">
			<h3 class="team__name">Mike Coolbert</h3>
			<span class="team__ocupation">Sales Manager</span>
			<p class="team__text">
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio recusandae doloribus ut fugit officia voluptate soluta.
			</p>
		</div>
	</div>
</section>
