<section class="link-back link-back--bg-light">
	<div class="page__inner">
		<a class="link-back__btn" href="/">Home</a>
		<span class="link-back--mx">/</span>
		<span class="link-back--mx">Cart</span>
	</div>
</section>

<section class="page__inner page__section">
	<div class="page__overflow-x">
		<table class="table">
			<thead>
				<tr>
					<th class="table__item table__item-header">Image</th>
					<th class="table__item table__item-header">Product</th>
					<th class="table__item table__item-header">Price</th>
					<th class="table__item table__item-header">Quantity</th>
					<th class="table__item table__item-header">Total</th>
					<th class="table__item table__item-header">Remove</th>						
				</tr>
			</thead>

			<tbody>
				<tr>
					<td class="table__item"><img class="table__img" src="images/cloth_1.jpg"></td>
					<td class="table__item">Top Up T-Shirt</td>
					<td class="table__item">$49.00</td>
					<td class="table__item">
						<div class="table__rel">
							<button class="btn btn__input btn--white-2 btn__input--left">-</button>

							<input class="input input--center input--no-margin" type="text" value="1">

							<button class="btn btn__input btn--white-2">+</button>
						</div>
					</td>
					<td class="table__item">$49.00</td>
					<td class="table__item"><a class="btn btn--size-sm" href="#"><i class="fas fa-times"></i></a></td>
				</tr>

				<tr>
					<td class="table__item"><img class="table__img" src="images/cloth_2.jpg"></td>
					<td class="table__item">Polo Shirt</td>
					<td class="table__item">$49.00</td>
					<td class="table__item">
						<div class="table__rel">
							<button class="btn btn__input btn--white-2 btn__input--left">-</button>

							<input class="input input--center input--no-margin" type="text" value="1">

							<button class="btn btn__input btn--white-2">+</button>
						</div>
					</td>
					<td class="table__item">$49.00</td>
					<td class="table__item"><a class="btn btn--size-sm" href="#"><i class="fas fa-times"></i></a></td>
				</tr>
			</tbody>
		</table>
	</div>

	<div class="grid grid--col-5-3 grid--gap-2">
		<div>
			<div class="grid grid--col-2">
				<button class="btn btn--size-md input__btn">Update Cart</button>
				<button class="btn btn--size-md input__btn btn--white-2">Continue Shopping</button>
			</div>

			<div class="">
				<h3 class="title__sub">Coupon</h3>
				<p class="title__lines">Enter your coupon code if you have one.</p>
				<input class="input" type="text" placeholder="Coupon Code">
				<button class="btn btn--size-md">Apply Coupon</button>
			</div>
		</div>

		<div class="">
			<h3 class="title__sub title__sub--right">Cart Totals</h3>
			<p class="title__lines title__lines flex">Subtotal <span>$230.00</span></p>
			<p class="title__lines flex">Total <span>$230.00</span></p>

			<a href="/checkout" class="btn btn--size-md input__btn">Proceed to checkout</a>
		</div>
	</div>
</section>
