<section class="page page-check">
	<div class="container">
		<a href="index.html">Home</a>
		<span>/</span>Cart
	</div>
</section>

<section class="cart container">
	<div class="cart__table">
		<table>
			<tr>
				<th>Image</th>
				<th>Product</th>
				<th>Price</th>
				<th>Quantity</th>
				<th>Total</th>
				<th>Remove</th>						
			</tr>

			<tr>
				<td><img src="images/cloth_1.jpg"></td>
				<td>Top Up T-Shirt</td>
				<td>$49.00</td>
				<td>
					<div class="table-btn">
						<button>-</button>

						<input type="text" value="1">

						<button>+</button>
					</div>
				</td>
				<td>$49.00</td>
				<td><a href="#"><i class="fas fa-times"></i></a></td>
			</tr>

			<tr>
				<td><img src="images/cloth_2.jpg"></td>
				<td>Polo Shirt</td>
				<td>$49.00</td>
				<td>
					<div class="table-btn">
						<button>-</button>

						<input type="text" value="1">

						<button>+</button>
					</div>
				</td>
				<td>$49.00</td>
				<td><a href="#"><i class="fas fa-times"></i></a></td>
			</tr>
		</table>
	</div>

	<div class="cart__total">
		<div>
			<div class="total-btn">
				<button>Update Cart</button>
				<button>Continue Shopping</button>
			</div>

			<div class="total-coupon">
				<h3>Coupon</h3>
				<p>Enter your coupon code if you have one.</p>
				<input type="text" placeholder="Coupon Code">
				<button>Apply Coupon</button>
			</div>
		</div>

		<div class="total-check">
			<h3>Cart Totals</h3>
			<p>Subtotal <span>$230.00</span></p>
			<p>Total <span>$230.00</span></p>

			<a href="checkout.html">Proceed to checkout</a>
		</div>
	</div>
</section>
