<section class="banner-contact">
</section>

<section class="page">
	<div class="container">
		<a href="index.html">Home</a>
		<span>/</span>
		<span>Contact</span>
	</div>
</section>

<section class="contact container">
	<h2>Get In Touch</h2>

	<div class="contact__container">
		<div class="contact__form">
			<form>
				<div class="contact__form__name">
					<div>
						<label>First Name<span>*</span></label>
						<input type="text" required>
					</div>

					<div>
						<label>Last Name<span>*</span></label>
						<input type="text" required>
					</div>
				</div>

				<label>Email<span>*</span></label>
				<input type="email">

				<label>Subject</label>
				<input type="text">

				<label>Message</label>
				<textarea rows="10"></textarea>

				<button type="submit">Send Message</button>
			</form>
		</div>

		<div class="contact__address">
			<div>
				<h3>New York</h3>
				<address>203 Fake St. Mountain View, San Francisco, California, USA</address>
			</div>

			<div>
				<h3>London</h3>
				<address>203 Fake St. Mountain View, San Francisco, California, USA</address>
			</div>

			<div>
				<h3>Canada</h3>
				<address>203 Fake St. Mountain View, San Francisco, California, USA</address>
			</div>
		</div>
	</div>
</section>


