<section class="banner">
	<div class="page__inner grid grid--autofit grid--gap-2">
		<div class="banner__content">
			<h2 class="banner__sub">#New summer collection 2019</h2>
			<h1 class="banner__title">Arrivals sales</h1>
			<a class="btn btn--size-md btn--black" href="#">Shop now</a>
		</div>

		<div class="banner__img">
			<img src="images/model_3.png">
		</div>				
	</div>
</section>

<section class="page__inner page__section"><!-- Discover start -->
	<div class="title">
		<h2 class="title__text">Discover<div> the collections</div></h2>
	</div>

	<div class="discover grid grid--gap-2 grid--col-5-3">
		<div class="discover__itens discover__itens--height">
			<img src="images/model_4.png">
			<a class="btn btn--size-md btn--white discover__btn" href="#">Women<small class="discover__inside"> 25 itens</small></a>
		</div>

		<div class="discover__content grid">
			<div class="discover__itens">
				<img src="images/model_5.png">
				<a class="btn btn--size-md btn--white discover__btn" href="#">Men<small class="discover__inside"> 25 itens</small></a>
			</div>

			<div class="discover__itens">
				<img src="images/model_6.png">
				<a class="btn btn--size-md btn--white discover__btn" href="#">Shoes<small class="discover__inside"> 25 itens</small></a>
			</div>
		</div>
	</div>
</section><!-- Discover end -->

<section class="page__inner page__section"><!-- Popular star -->
	<div class="title">
		<h2 class="title__text">Popular products</h2>
	</div>

	<div class="grid grid--autofit grid--gap-2">
		<div class="product">
			<a class="product__link" href="#">
				<img class="product__img" src="images/prod_2.png">
			</a>
		
			<h2 class="product__name">Gray Shoe</h2>
			<p class="product__price">$20.00</p>
		</div>

		<div class="product">
			<a class="product__link" href="#">
				<img class="product__img" src="images/prod_3.png">
			</a>
			
			<h2 class="product__name">Blue Shoe High Heels</h2>
			<p class="product__price"><span class="product__price--sale">$46.00</span>$28.00</p>
		</div>

		<div class="product">
			<a class="product__link" href="#">
				<img class="product__img" src="images/model_5.png">
			</a>

			<h2 class="product__name">Denim Jacket</h2>
			<p class="product__price"><span class="product__price--sale">$46.00</span>$28.00</p>
			<div class="product__star">
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
			</div>
		</div>

		<div class="product">
			<a class="product__link" href="#">
				<img class="product__img" src="images/prod_1.png">
			</a>

			<h2 class="product__name">Leather Green Bag</h2>
			<p class="product__price"><span class="product__price--sale">$46.00</span>$28.00</p>
			<div class="product__star">
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
			</div>
		</div>

		<div class="product">
			<a class="product__link" href="#">
				<img class="product__img" src="images/model_1.png">
			</a>

			<h2 class="product__name">Smooth Cloth</h2>
			<p class="product__price"><span class="product__price--sale">$46.00</span>$28.00</p>
		</div>

		<div class="product">
			<a class="product__link" href="#">
				<img class="product__img" src="images/model_7.png">
			</a>

			<h2 class="product__name">Yellow Jacket</h2>
			<p class="product__price">$58.00</p>
		</div>
	</div>
</section><!-- Popular end -->

<section class="page__inner page__section">
	<div class="title">
		<h2 class="title__text">Most rated</h2>
	</div>

	<div class="swiper-container">
		<div class="swiper-wrapper">
			<div class="product swiper-slide">			
				<a class="product__link" href="#">
					<img class="product__img" src="images/model_1.png">
				</a>			

				<h2 class="product__name">Smooth Cloth</h2>
				<p class="product__price"><span class="product__price--sale">$46.00</span>$28.00</p>
				<div class="product__star">
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
				</div>
			</div>

			<div class="product swiper-slide">			
				<a class="product__link" href="#">
					<img class="product__img" src="images/prod_3.png">
				</a>			

				<h2 class="product__name">Blue Shoe High Heels</h2>
				<p class="product__price"><span class="product__price--sale">$46.00</span>$28.00</p>
				<div class="product__star">
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
				</div>
			</div>

			<div class="product swiper-slide">			
				<a class="product__link" href="#">
					<img class="product__img" src="images/model_5.png">
				</a>			

				<h2 class="product__name">Denim Jacket</h2>
				<p class="product__price"><span class="product__price--sale">$46.00</span>$28.00</p>
				<div class="product__star">
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
				</div>
			</div>

			<div class="product swiper-slide">
				<a class="product__link" href="#"><img class="product__img" src="images/prod_1.png"></a>

				<h2 class="product__name">Leather Green Bag</h2>
				<p class="product__preco"><span class="product__price--sale">$46.00</span>$28.00</p>
				<div class="product__star">
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
				</div>
			</div>

			<div class="product swiper-slide">
				<a class="product__link" href="#"><img class="product__img" src="images/model_7.png"></a>

				<h2 class="product__name">Yellow Jacket</h2>
				<p class="product__preco">$58.00</p>
				<div class="product__star">
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="banner">
	<div class="page__inner grid grid--autofit grid--gap-2"">
		<div class="banner__content">
			<h2 class="banner__sub">#New Summer Collection 2019</h2>
			<h1 class="banner__title">New Shoes</h1>
			<a class="btn btn--size-md btn--black" href="#">Shop Now</a>
		</div>

		<div class="banner__img">
			<img src="images/model_6.png">			
		</div>
	</div>
</section>



