<section class="banner">
	<div class="container banner__container">
		<div class="banner__content">
			<h2>#New summer collection 2019</h2>
			<h1>Arrivals sales</h1>
			<a href="#">Shop now</a>
		</div>

		<div class="banner__img">
			<img src="images/model_3.png">
		</div>				
	</div>
</section>

<section class="discover container">
	<div class="title">
		<h2>Discover<span>the collections</span></h2>
	</div>

	<div class="discover__container">
		<div class="discover__itens discover__women">
			<img src="images/model_4.png">
			<a href="#">Women<small>25 itens</small></a>
		</div>

		<div>
			<div class="discover__itens">
				<img src="images/model_5.png">
				<a href="#">Men<small>25 itens</small></a>
			</div>

			<div class="discover__itens">
				<img src="images/model_6.png">
				<a href="#">Shoes<small>25 itens</small></a>
			</div>
		</div>
	</div>
</section>

<section class="popular container">
	<div class="title">
		<h2>Popular products</h2>
	</div>

	<div class="popular__container">
		<div class="popular__itens">
			<a href="#">
				<img src="images/prod_2.png">
			</a>
		
			<h2>Gray Shoe</h2>
			<p>$20.00</p>
		</div>

		<div class="popular__itens">
			<a href="#">
				<img src="images/prod_3.png">
			</a>
			
			<h2>Blue Shoe High Heels</h2>
			<p><span>$46.00</span>$28.00</p>
		</div>

		<div class="popular__itens">
			<a href="#">
				<img src="images/model_5.png">
			</a>

			<h2>Denim Jacket</h2>
			<p><span>$46.00</span>$28.00</p>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
		</div>

		<div class="popular__itens">
			<a href="#">
				<img src="images/prod_1.png">
			</a>

			<h2>Leather Green Bag</h2>
			<p><span>$46.00</span>$28.00</p>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
		</div>

		<div class="popular__itens">
			<a href="#">
				<img src="images/model_1.png">
			</a>

			<h2>Smooth Cloth</h2>
			<p><span>$46.00</span>$28.00</p>
		</div>

		<div class="popular__itens">
			<a href="#">
				<img src="images/model_7.png">
			</a>

			<h2>Yellow Jacket</h2>
			<p>$58.00</p>
		</div>
	</div>
</section>

<section class="rated container">
	<div class="title">
		<h2>Most rated</h2>
	</div>

	<div class="rated__container">
		<div class="rated__itens">
			<div>
				<a href="#"><img src="images/model_1.png"></a>
			</div>

			<h2>Smooth Cloth</h2>
			<p><span>$46.00</span>$28.00</p>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
		</div>

		<div class="rated__itens">
			<div>
				<a href="#"><img src="images/prod_3.png"></a>
			</div>

			<h2>Blue Shoe High Heels</p></h2>
			<p><span>$46.00</span>$28.00</p>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
		</div>

		<div class="rated__itens">
			<div>
				<a href="#"><img src="images/model_5.png"></a>
			</div>

			<h2>Denim Jacket</p></h2>
			<p><span>$46.00</span>$28.00</p>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
		</div>

		<div class="rated__itens">
			<div>
				<a href="#"><img src="images/prod_1.png"></a>
			</div>

			<h2>Leather Green Bag</p></h2>
			<p><span>$46.00</span>$28.00</p>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
		</div>

		<div class="rated__itens">
			<div>
				<a href="#"><img src="images/model_7.png"></a>
			</div>

			<h2>Yellow Jacket</p></h2>
			<p>$58.00</p>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
			<i class="fas fa-star"></i>
		</div>
		<div style="clear: both"></div>
	</div>
	

	<div class="rated__btn">
		<button class="btn-prev"><i class="fas fa-arrow-left"></i></button>
		<button class="btn-next"><i class="fas fa-arrow-right"></i></button>
	</div>
</section>

<section class="banner">
	<div class="container banner__container">
		<div class="banner__content">
			<h2>#New Summer Collection 2019</h2>
			<h1>New Shoes</h1>
			<a href="#">Shop Now</a>
		</div>

		<div class="banner__img">
			<img src="images/model_6.png">			
		</div>
	</div>
</section>



