<section class="page page-check">
	<div class="container">
		<a href="index.html">Home</a>
		<span>/</span>Login
	</div>
</section>

<section class="login container">
	<h2>Login</h2>

	<label>Username or email address *</label>
	<input type="text" required>
	
	<label>Password *</label>
	<input type="password" required>

	<div>
		<label>
			<input type="checkbox">Save Password
		</label>

		<a href="#">Forget your Password?</a>
	</div>

	<a href="#" class="login__sign">Sign in</a>
	<a href="register.html" class="login__link">Or create an account</a>
</section>
