<section class="page page-check">
	<div class="container">
		<a href="index.html">Home</a>
		<span>/</span>Register
	</div>
</section>

<section class="login container">
	<h2>Register</h2>

	<label>Username or email address</label>
	<input type="text" required>
	
	<label>Password</label>
	<input type="password" required>

	<label>Confirm Password</label>
	<input type="password" required>

	<a href="#" class="login__sign">Register</a>
	<a href="login.html" class="login__link">Or login</a>
</section>

