<section class="link-back link-back--bg-light">
	<div class="page__inner">
		<a class="link-back__btn" href="/">Home</a>
		<span class="link-back--mx">/</span>
		<span class="link-back--mx">Register</span>
	</div>
</section>

<section class="user page__user page__section">
	<h2 class="user__title">Register</h2>

	<label>Username or email address</label>
	<input class="input" type="text" required>
	
	<label>Password</label>
	<input class="input" type="password" required>

	<label>Confirm Password</label>
	<input class="input" type="password" required>

	<a href="#" class="btn btn--size-md input__btn">Register</a>
	<a href="/login" class="user__link">Or login</a>
</section>

