<section class="banner">
	<div class="page__inner grid grid--autofit grid--gap-2">
		<div class="banner__content">
			<h2 class="banner__sub">#New summer collection 2019</h2>
			<h1 class="banner__title">Arrivals sales</h1>
			<a class="btn btn--size-md btn--black" href="#">Shop now</a>
		</div>

		<div class="banner__img">
			<img src="images/model_4.png">
		</div>				
	</div>
</section>

<section class="link-back">
	<div class="page__inner">
		<a class="link-back__btn" href="/">Home</a>
		<span class="link-back--mx">/</span>
		<span class="link-back--mx">Shop</span>
	</div>
</section>

<section class="filter page__inner page__section">
	<div class="grid grid--gap-2 grid--col-3-1">
		<div>
			<div class="filter__options flex">
				<h3 class="filter__title">Shop All</h3>

				<div>
					<select class="filter__selection">
						<option value="">Latest</option>
						<option value="men">Men</option>
						<option value="women">Women</option>
						<option value="children">Children</option>
					</select>

					<select class="filter__selection">
						<option value="">Relevance</option>
						<option value="nameA">Name, A to Z</option>
						<option value="nameZ">Name, Z to A</option>
						<option value="priceL">Price, low to high</option>
						<option value="priceH">Price, high to low</option>
					</select>
				</div>
			</div>

			<div class="grid grid--autofit grid--gap-2">
				<div class="product">
					<a class="product__link" href="#"><img class="product__img" src="images/prod_2.png"></a>
					<h2 class="product__name">Gray Shoe</h2>
					<p class="product__price">$20.00</p>
				</div>

				<div class="product">
					<a class="product__link" href="#"><img class="product__img" src="images/prod_3.png"></a>
					<h2 class="product__name">Blue Shoe High Heels</h2>
					<p class="product__price"><span class="product__price--sale">$46.00</span>$28.00</p>
				</div>

				<div class="product">
					<a class="product__link" href="#"><img class="product__img" src="images/model_5.png"></a>
					<h2 class="product__name">Denim Jacket</h2>
					<p class="product__price"><span class="product__price--sale">$46.00</span>$28.00</p>
					<div class="product__star">
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
					</div>
				</div>

				<div class="product">
					<a class="product__link" href="#"><img class="product__img" src="images/prod_1.png"></a>
					<h2 class="product__name">Leather Green Bag</h2>
					<p class="product__price"><span class="product__price--sale">$46.00</span>$28.00</p>
					<div class="product__star">
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
					</div>
				</div>

				<div class="product">
					<a class="product__link" href="#"><img class="product__img" src="images/model_1.png"></a>
					<h2 class="product__name">Smooth Cloth</h2>
					<p class="product__price"><span class="product__price--sale">$46.00</span>$28.00</p>
				</div>

				<div class="product">
					<a class="product__link" href="#"><img class="product__img" src="images/model_7.png"></a>
					<h2 class="product__name">Yellow Jacket</h2>
					<p class="product__price">$58.00</p>
				</div>

				<div class="product">
					<a class="product__link" href="#"><img class="product__img" src="images/prod_2.png"></a>
					<h2 class="product__name">Gray Shoe</h2>
					<p class="product__price">$20.00</p>
				</div>

				<div class="product">
					<a class="product__link" href="#"><img class="product__img" src="images/prod_3.png"></a>
					<h2 class="product__name">Blue Shoe High Heels</h2>
					<p class="product__price"><span class="product__price--sale">$46.00</span>$28.00</p>
				</div>

				<div class="product">
					<a class="product__link" href="#"><img class="product__img" src="images/model_5.png"></a>
					<h2 class="product__name">Denim Jacket</h2>
					<p class="product__price"><span class="product__price--sale">$46.00</span>$28.00</p>
					<div class="product__star">
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
					</div>
				</div>

				<div class="product">
					<a class="product__link" href="#"><img class="product__img" src="images/prod_1.png"></a>
					<h2 class="product__name">Leather Green Bag</h2>
					<p class="product__price"><span class="product__price--sale">$46.00</span>$28.00</p>
					<div class="product__star">
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
					</div>
				</div>

				<div class="product">
					<a class="product__link" href="#"><img class="product__img" src="images/model_1.png"></a>
					<h2 class="product__name">Smooth Cloth</h2>
					<p class="product__price"><span class="product__price--sale">$46.00</span>$28.00</p>
				</div>

				<div class="product">
					<a class="product__link" href="#"><img class="product__img" src="images/model_7.png"></a>
					<h2 class="product__name">Yellow Jacket</h2>
					<p class="product__price">$58.00</p>
				</div>
			</div>

			<div class="pagination">
				<a class="pagination__btn" href="#"><span class="pagination__centerY"><</span></a>
				<a class="pagination__btn pagination__btn--active" href="#"><span class="pagination__centerY">1</span></a>
				<a class="pagination__btn" href="#"><span class="pagination__centerY">2</span></a>
				<a class="pagination__btn" href="#"><span class="pagination__centerY">3</span></a>
				<a class="pagination__btn" href="#"><span class="pagination__centerY">4</span></a>
				<a class="pagination__btn" href="#"><span class="pagination__centerY">5</span></a>
				<a class="pagination__btn" href="#"><span class="pagination__centerY">></span></a>
			</div>
		</div>

		<div>
			<div class="box">
				<h3 class="filter__name">Categories</h3>
				
				<ul>
					<li><a class="filter__link flex" href="#">Men<span>(2,220)</span></a></li>
					<li><a class="filter__link flex" href="#">Women<span>(2,550)</span></a></li>
					<li><a class="filter__link flex" href="#">Children<span>(2,124)</span></a></li>
				</ul>
			</div>

			<div class="box">
				<h3 class="filter__name">Filter by price</h3>
				<div class="flex flex--relative">
					<input class="filter__input" type="number" name="quantity" min="0" placeholder="Min"> 
					<span class="filter__space">-</span>
					<input class="filter__input" type="number" name="quantity" min="0" placeholder="Max">
				</div>
				<h3 class="filter__name filter__name--mt-2">Size</h3>

				<label class="filter__check">
					<input type="checkbox" name="size" value="small"><span class="filter__check-size">Small(2,319)</span>
				</label>

				<label class="filter__check">
					<input type="checkbox" name="size" value="medium"><span class="filter__check-size">Medium(1,282)</span>
				</label>

				<label class="filter__check">
					<input type="checkbox" name="size" value="large"><span class="filter__check-size">Large(1,392)</span>
				</label>


				<div class="">
					<h3 class="filter__name filter__name--mt-2">Color</h3>

					<a class="filter__link-color" href="#">
						<span class="filter__color filter__color--red"></span>
						<span>Red(2,429)</span>
					</a>

					<a class="filter__link-color" href="#">
						<span class="filter__color filter__color--green"></span>
						<span>Green(2,298)</span>
					</a>

					<a class="filter__link-color" href="#">
						<span class="filter__color filter__color--blue"></span>
						<span>Blue(1,075)</span>
					</a>

					<a class="filter__link-color" href="#">
						<span class="filter__color filter__color--purple"></span>
						<span>Purple(1,075)</span>
					</a>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="page__inner page__section"><!-- Discover start -->
	<div class="title">
		<h2 class="title__text">Discover<div> the collections</div></h2>
	</div>

	<div class="discover grid grid--gap-2 grid--col-5-3">
		<div class="discover__itens discover__itens--height">
			<img src="images/model_4.png">
			<a class="btn btn--size-md btn--white discover__btn" href="#">Women<small class="discover__inside"> 25 itens</small></a>
		</div>

		<div class="discover__content grid">
			<div class="discover__itens">
				<img src="images/model_5.png">
				<a class="btn btn--size-md btn--white discover__btn" href="#">Men<small class="discover__inside"> 25 itens</small></a>
			</div>

			<div class="discover__itens">
				<img src="images/model_6.png">
				<a class="btn btn--size-md btn--white discover__btn" href="#">Shoes<small class="discover__inside"> 25 itens</small></a>
			</div>
		</div>
	</div>
</section><!-- Discover end -->
