<section class="banner">
	<div class="container banner__container">
		<div class="banner__content">
			<h2>#New summer collection 2019</h2>
			<h1>Arrivals sales</h1>
			<a href="#">Shop now</a>
		</div>

		<div class="banner__img-shop">
			<img src="images/model_4.png">
		</div>				
	</div>
</section>

<section class="page">
	<div class="container">
		<a href="index.html">Home</a>
		<span>/</span>
		<span>Shop</span>
	</div>
</section>

<section class="shop container">
	<div class="shop__product">
		<div class="shop__product__filter">
			<h3>Shop All</h3>

			<div>
				<select>
					<option value="">Latest</option>
					<option value="men">Men</option>
					<option value="women">Women</option>
					<option value="children">Children</option>
				</select>

				<select>
					<option value="">Relevance</option>
					<option value="nameA">Name, A to Z</option>
					<option value="nameZ">Name, Z to A</option>
					<option value="priceL">Price, low to high</option>
					<option value="priceH">Price, high to low</option>
				</select>
			</div>
		</div>

		<div class="shop__container">
			<div class="shop__itens">
				<a href="#"><img src="images/prod_2.png"></a>
				<h2>Gray Shoe</h2>
				<p>$20.00</p>
			</div>

			<div class="shop__itens">
				<a href="#"><img src="images/prod_3.png"></a>
				<h2>Blue Shoe High Heels</h2>
				<p><span>$46.00</span>$28.00</p>
			</div>

			<div class="shop__itens">
				<a href="#"><img src="images/model_5.png"></a>
				<h2>Denim Jacket</h2>
				<p><span>$46.00</span>$28.00</p>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
			</div>

			<div class="shop__itens">
				<a href="#"><img src="images/prod_1.png"></a>
				<h2>Leather Green Bag</h2>
				<p><span>$46.00</span>$28.00</p>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
			</div>

			<div class="shop__itens">
				<a href="#"><img src="images/model_1.png"></a>
				<h2>Smooth Cloth</h2>
				<p><span>$46.00</span>$28.00</p>
			</div>

			<div class="shop__itens">
				<a href="#"><img src="images/model_7.png"></a>
				<h2>Yellow Jacket</h2>
				<p>$58.00</p>
			</div>

			<div class="shop__itens">
				<a href="#"><img src="images/prod_2.png"></a>
				<h2>Gray Shoe</h2>
				<p>$20.00</p>
			</div>

			<div class="shop__itens">
				<a href="#"><img src="images/prod_3.png"></a>
				<h2>Blue Shoe High Heels</h2>
				<p><span>$46.00</span>$28.00</p>
			</div>

			<div class="shop__itens">
				<a href="#"><img src="images/model_5.png"></a>
				<h2>Denim Jacket</h2>
				<p><span>$46.00</span>$28.00</p>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
			</div>

			<div class="shop__itens">
				<a href="#"><img src="images/prod_1.png"></a>
				<h2>Leather Green Bag</h2>
				<p><span>$46.00</span>$28.00</p>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
				<i class="fas fa-star"></i>
			</div>

			<div class="shop__itens">
				<a href="#"><img src="images/model_1.png"></a>
				<h2>Smooth Cloth</h2>
				<p><span>$46.00</span>$28.00</p>
			</div>

			<div class="shop__itens">
				<a href="#"><img src="images/model_7.png"></a>
				<h2>Yellow Jacket</h2>
				<p>$58.00</p>
			</div>
		</div>

		<div class="shop__product__btn">
			<a href="#"><span><</span></a>
			<a href="#" class="actived"><span>1</span></a>
			<a href="#"><span>2</span></a>
			<a href="#"><span>3</span></a>
			<a href="#"><span>4</span></a>
			<a href="#"><span>5</span></a>
			<a href="#"><span>></span></a>
		</div>
	</div>

	<div class="shop__filter">
		<div class="shop__filter__itens">
			<h3>Categories</h3>
			
			<ul>
				<li><a href="#">Men<span>(2,220)</span></a></li>
				<li><a href="#">Women<span>(2,550)</span></a></li>
				<li><a href="#">Children<span>(2,124)</span></a></li>
			</ul>
		</div>

		<div class="shop__filter__itens">
			<h3>Filter by price</h3>

			<input type="number" name="quantity" min="0" placeholder="Min">
			<input type="number" name="quantity" min="0" placeholder="Max">

			<h3>Size</h3>

			<label>
				<input type="checkbox" name="size" value="small"><span>Small(2,319)</span>
			</label>

			<label>
				<input type="checkbox" name="size" value="medium"><span>Medium(1,282)</span>
			</label>

			<label>
				<input type="checkbox" name="size" value="large"><span>Large(1,392)</span>
			</label>


			<div class="shop__filter__color">
				<h3>Color</h3>

				<a href="#">
					<span style="background-color: red"></span>
					<span>Red(2,429)</span>
				</a>

				<a href="#">
					<span style="background-color: green"></span>
					<span>Green(2,298)</span>
				</a>

				<a href="#">
					<span style="background-color: blue"></span>
					<span>Blue(1,075)</span>
				</a>

				<a href="#">
					<span style="background-color: purple"></span>
					<span>Purple(1,075)</span>
				</a>
			</div>
		</div>
	</div>
</section>

<section class="discover container">
	<div class="title">
		<h2>Discover<span>the collections</span></h2>
	</div>

	<div class="discover__container">
		<div class="discover__itens discover__women">
			<img src="images/model_4.png">
			<a href="#">Women<small>25 itens</small></a>
		</div>

		<div>
			<div class="discover__itens">
				<img src="images/model_5.png">
				<a href="#">Men<small>25 itens</small></a>
			</div>

			<div class="discover__itens">
				<img src="images/model_6.png">
				<a href="#">Shoes<small>25 itens</small></a>
			</div>
		</div>
	</div>
</section>
