<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>ShopMax</title>		

		<!-- Font Awesome -->
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">

		<!-- JQuery -->
		<script src="https://code.jquery.com/jquery-3.4.1.min.js"
		integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
		crossorigin="anonymous"></script>

		<link rel="stylesheet" type="text/css" href="/css/style.css">
		<link rel="stylesheet" type="text/css" href="/css/main.css">

	</head>

	<body>
		<header class="header container">
			<div class="header__search">
				<input type="text" placeholder="Search keyword and hit enter...">
				<a class="close-search" href="#"><i class="fas fa-times"></i></a>
			</div>

			<h1><a href="/">Shopmax</a></h1>

			<nav class="header__navbar">
				<ul>
					<li>
						<div class="home-actived">
							<button class="home-btn"><i class="fas fa-arrow-down"></i></button>
							<a class="actived home-hover" href="/">Home</a>
						</div>
						<ul class="dropdown">
							<li><a href="/about">About</a></li>
							<li><a href="#">Menu Two</a></li>
							<li><a href="#">Menu Three</a></li>
							<li>
								<div>
									<button class="submenu-btn"><i class="fas fa-arrow-down"></i></button> 
									<a class="submenu-hover" href="#">Sub Menu</a>
								</div>
								<ul class="dropdown__sub">
									<li><a href="#">Menu One</a></li>
									<li><a href="#">Menu Two</a></li>
									<li><a href="#">Menu Three</a></li>
								</ul>
							</li>
						</ul>
					</li>
					<li><a href="/shop">Shop</a></li>
					<li><a href="#">Catalogue</a></li>
					<li><a href="#">New Arrivals</a></li>
					<li><a href="/contact">Contact</a></li>
				</ul>
			</nav>

			<div class="header__icons">
				<a class="search-btn" href="#"><i class="fas fa-search"></i></a>
				<a href="#"><i class="far fa-heart"></i></a>
				<a href="/cart" class="bag"><i class="fas fa-shopping-bag"><span>2</span></i></a>
				<button><i class="fas fa-bars"></i></button>
				<a href="/login"><i class="fas fa-user"></i>Login</a>
			</div>
		</header>

		<?= $this->content() ?>

		<footer class="footer container">
			<div class="footer__container">
				<div class="footer__content">
					<h3>Promo</h3>
					<a href="#"><img src="images/about_1.jpg"></a>
					<a href="#">
						<h3>Finding Your Perfect Shirts This Summer</h3>
						<p>Promo from July 15 - 25, 2019</p>
					</a>
				</div>

				<div class="footer__links">
					<h3>Quick Links</h3>

					<div class="footer__links__grid">
						<div>
							<ul>
								<li><a href="#">Sell online</a></li>
								<li><a href="#">Features</a></li>
								<li><a href="#">Shopping cart</a></li>
								<li><a href="#">Store builder</a></li>
							</ul>
						</div>

						<div>
							<ul>
								<li><a href="#">Mobile commerce</a></li>
								<li><a href="#">Dropshipping</a></li>
								<li><a href="#">Website development</a></li>
							</ul>
						</div>

						<div>
							<ul>
								<li><a href="#">Point of sale</a></li>
								<li><a href="#">Hardware</a></li>
								<li><a href="#">Software</a></li>
							</ul>
						</div>
					</div>
				</div>

				<div class="footer__contact">
					<h3>Contact info</h3>

					<div>
						<i class="fas fa-map-marker-alt"></i><address>203 Fake St. Mountain View, San Francisco, California, USA</address>
					</div>

					<div>
						<i class="fas fa-phone-alt"></i><address>+2 392 3929 210</address>
					</div>

					<div>
						<i class="fas fa-envelope"></i><address>emailaddress@domain.com</address>
					</div>

					<h3>Subscribe</h3>

					<div class="footer__contact__form">
						<input type="email" placeholder="Email">
						<input type="submit" value="Send">
					</div>
				</div>
			</div>

			<div class="footer__copy">
				<p>Copyright ©2020 All rights reserved | This template is made with  by Colorlib</p>
			</div>
		</footer>
	</body>

</html>